#项目名称
spring:
  application:
    name: micr-dataservice
  redis:
    host: localhost
    port: 6379


#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ylb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123


#mybatis
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#dubbo
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.nuguseiyou.dataservice.service
  provider:
    #最大超时时间
    timeout: 100000
    #超时重试的次数
    #retries: 0

mima:
  salt: xibalaoma

