spring:
  application:
    name: micr-pay
  thymeleaf:
    cache: false

server:
  port: 9000
  servlet:
    context-path: /pay

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.nuguseiyou
  consumer:
    timeout: 10000
    check: false
