server:
  port: 9000
  servlet:
    context-path: /pay


spring:
  thymeleaf:
    cache: false
  application:
    name: micr-pay

dubbo:
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
    timeout: 10000
  scan:
    base-packages: com.bjpowernode