spring:
  application:
    name: micr-task


dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.nuguseiyou
  consumer:
    timeout: 100000
    #是否检查提供者
    check: false
